### ISSUE TITLE
Copying plugin files to child theme for customization prompts error

### ISSUE THREAD

**Issue by EmerKelly** [ComeetCo/comeet-wp-plugin#11]
I have followed the instructions for customizing the plugin files. I created a folder 'comeet' in my child theme and copied the files in there. Once I copy them, and before I even make any customizations, I get this error:

Warning: include(/code/wp-content/themes/hello-theme-child-master/comeet): failed to open stream: No such file or directory in /code/wp-includes/template-loader.php on line 106 Warning: include(): Failed opening '/code/wp-content/themes/hello-theme-child-master/comeet/' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /code/wp-includes/template-loader.php on line 106

You can see it live here: https://dev-deepc.pantheonsite.io/job-opportunities/co/boston/F2.B24/scientific-software-engineer/all/

Any ideas on how to solve this? Is this happening to anybody else?

**Comment by YonatanRan** [comment]
Hi @EmerKelly.
I have heard of one other person (so far) that has had this issue.
Can you check what permissions the files in the theme folder have? Additionally can you tell me what version of the plugin you have + Wordpress?

Thanks.

**Comment by YonatanRan** [comment]
@EmerKelly Can you please do the following, it will help me to try and understand the issue and fix it.
In the file names comeet.php on line 363 add the following:
$this->plugin_debug("Template file is: ".$template,__LINE__, __FILE__);
This should be in a function named: "career_page_template" right before "return $template"

Thank you.

**Comment by EmerKelly** [comment]
Sure, it has been added

![Screen Shot 2022-03-07 at 12 48 08 PM](https://user-images.githubusercontent.com/15749524/157089318-d7a81432-09a6-4950-8db5-716cb031d359.png)

**Comment by YonatanRan** [comment]
@EmerKelly Can you please tell me what theme you are using? (I am having trouble recreating the issue and trying to pinpoint the cause)

Thanks.

**Comment by EmerKelly** [comment]
I'm using Hello Elementor with Elementor page builder. However, I have also tried it on a clean install of the 2021 Wordpress theme with all plugins deactivated and I get the same error. I am using Pantheon for hosting (https://pantheon.io/). I've spoken to them to see if it's a hosting/setup issue but they didn't think so.

**Comment by YonatanRan** [comment]
@EmerKelly  I appreciate all your help on this.
Can you tell me what files you copied into the theme comeet folder? (Copied from the templates into the comeet folder that is in your theme)

**Comment by EmerKelly** [comment]
No problem! Thank you for helping me work this out. I copied comeet-position-page.php and 'comeet-sub-page.php.' 

It doesn't seem to matter which files are in there thought. The problem seems to be the presence of the 'comeet' folder at all. I still get the error if the folder is empty, or if I copy ALL the template files to the folder.

**Comment by YonatanRan** [comment]
@EmerKelly The current solution (Not a good one obviously) is to make changes in the plugin itself.
This should allow you to make the changes you want and continue working with out having this issue/bug hold you back.
I am investigating and trying to re-create/fix the issue. I will update here once I have more information or a solution.

Thanks.

**Comment by EmerKelly** [comment]
ok thanks. That's what I did on the Live client site, just to keep everybody happy. I'm hoping we can find a more long-term solution soon.

Considering you're having trouble re-creating the issue, do you think my hosting provider _could_ have something to do with it? Pantheon configures sites a little differently than other hosting providers.

**Comment by EmerKelly** [comment]
Pantheon also have their own files they use with Wordpress. You can see them listed in this screenshot. I'm not sure if they are playing into this. I can give you more info on the file contents if you think it's relevant.
![Screen Shot 2022-03-10 at 1 38 16 PM](https://user-images.githubusercontent.com/15749524/157732216-b4d5a951-dc49-403a-85e3-0680c5053abe.png)

**Comment by EmerKelly** [comment]
Hi @YonatanRan. Did that information help? Let me know if there's anything else I can provide to help you track this down.

**Comment by YonatanRan** [comment]
Hi @EmerKelly Thanks.

Still can't recreate this. Final question (I hope) do you know what version of Linux your hosting provider has?

Thanks.

**Comment by YonatanRan** [comment]
@EmerKelly Yes, that would help a lot. Thanks!

**Comment by YonatanRan** [comment]
@EmerKelly My email is yonatan.ran@comeet.co for details.
I appreciate the help.

**Comment by YonatanRan** [comment]
@EmerKelly I have access (Thank you!) Can you change the permission level of the files so I can edit/make changes?

**Comment by EmerKelly** [comment]
@YonatanRan I just sent you an email with SFTP access so you should be good to go

**Comment by YonatanRan** [comment]
Hi @EmerKelly, 
Thanks to the access you granted me, I was able to track down the issue and fix it.
There is a new version out 2.3.3 which has in it the fix to the problem I found.
https://github.com/ComeetCo/comeet-wp-plugin/releases/tag/Version-2.3.3

The staging site you gave me access to has the older version of the plugin (2.3.2) but has the fix, so stuff is working as expected.

To be extra safe, I would install the new version of the plugin on your staging site, ensure that everything is working as you expect, and if so, apply changes to the production site.
On the staging site the template files being used are from the comeet folder in the themes folder.
I really appreciate the help and access that you gave as it made it possible to figure this out and fix.

Please let me know if you run into any issues or need anything.

Thanks!

**Comment by EmerKelly** [comment]
Thank you @YonatanRan! This is so great. All is working perfectly. Thanks for all your support and have a great weekend :)
