### ISSUE TITLE
Not supported for multisites?

### ISSUE THREAD

**Issue by seojake** [ComeetCo/comeet-wp-plugin#13]
Getting an error when activating on a multisite:

```
Deprecated: Required parameter $category follows optional parameter $sub in /app/plugins/comeet-wp-plugin-Version-2.3.9/comeet.php on line 1573

Fatal error: Cannot redeclare comeet_string_clean() (previously declared in /app/plugins/comeet-wp-plugin-Version-2.3.9/includes/lib/comeet-data.php:2) in /app/plugins/comeet-wp-plugin-Version-2.3.9/includes/lib/comeet-data.php on line 2
```
However, when uploading plugin directly to a non-multisite install - it works fine.

Has anyone had this issue?

**Comment by YonatanRan** [comment]
Hi @seojake 
I'll look into this.

Thanks for letting me know about this issue.

**Comment by YonatanRan** [comment]
Hi @seojake,
I created a multisite to test this and didn't encounter the issue you are describing.
I did encounter some other small warnings that appeared when the plugin is applied to a multi site and added a fix that should fix the issue you encountered (even though I didn't encounter it).

Please update the plugin to the latest version (2.4) that I just published and let me know if the issue you encountered is resolved or not.

Thank you!

Is there anything special
