### ISSUE TITLE
On options save i get error

### ISSUE THREAD

**Issue by vetzo** [ComeetCo/comeet-wp-plugin#14]
After the save i get this error:

Error: Options page comeet_options not found in the allowed options list.

Comeet Plugin version: 2.4
Wordpress version: 6.0.2
PHP version: 8.0.23

![image](https://user-images.githubusercontent.com/12562021/194001038-02f16c14-8a59-48bf-9812-a179ba298e79.png)

**Comment by YonatanRan** [comment]
Hi @vetzo I can't seem to recreate the issue.
Can you please try the following:
1. Go back and try and save again, see if the issue repeats itself.
2. Check your database, look in wp_options (your database table might be named differently) and search for anything Comeet, do you see anything?

Thank you.
