### ISSUE TITLE
Problem with disabled positions

### ISSUE THREAD

**Issue by webprom** [ComeetCo/comeet-wp-plugin#6]
When position is disabled on comeet, looks like the page remains on site, but the layout is broken, footer is not loading.

The code for a closed position is here: https://github.com/ComeetCo/comeet-wp-plugin/blob/master/templates/comeet-position-page-common.php on top. But it's destroying the template's layout.

The problem probably here with **exit**.

if (empty($this->post_data) || (isset($this->post_data) && (isset($this->post_data['status'])) && ($this->post_data['status'] == 404))) {
	$careerurl = site_url() . (isset($post) ? '/' . $post->post_name : '');
	//echo '<meta http-equiv="refresh" content="5; url=' . $careerurl .'" />';
	echo 'The position may have been closed or the link is incorrect. You will be redirected to the careers page, if nothing happens click <a href="' . $careerurl .'">here</a>.';
    //
	exit;
}
?>
----

Another problem is that jobs scheme markup remains on such pages, so google search console is returning errors.

How to fix?
Or any way to redirect empty positions?

Thanks.

**Comment by webprom** [comment]
changing **exit**; to **return**; seems to help! 
footer is loading normally, but maybe there are more implications?

**Comment by YonatanRan** [comment]
This issue has been fixed by removing the "exit" completely.
