### ISSUE TITLE
Sub-brand filtering not working

### ISSUE THREAD

**Issue by miket2marcom** [ComeetCo/comeet-wp-plugin#7]
I am trying to filter certain positions using the Comeet plugin's sub-brand settings, but when I select the "sub-brand field", the dropdown for "select sub-brand" disappears (see attached screenshot).

<img width="571" alt="Screen Shot 2021-09-15 at 11 44 16 AM" src="https://user-images.githubusercontent.com/45983835/133465898-917d461a-3113-4218-a6a6-60c64c6e25b0.png">

I am expecting to see this dropdown have the "True" or "False" options that we gave that field in our Comeet account, but this dropdown just disappears entirely.

Any help here would be appreciated.

**Comment by YonatanRan** [comment]
Issue has been fixed in the latest version (Version-2.18.5) that can be found here:
https://github.com/ComeetCo/comeet-wp-plugin/releases/tag/Version-2.18.5
